version: 2

jobs:
  build:
    docker:
      - image: circleci/elixir:1.11
    working_directory: ~/repo
    steps:
      - checkout
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - restore_cache:
          keys:
            - v1-dependency-cache-{{ checksum "mix.lock" }}
            - v1-dependency-cache
      - restore_cache:
          keys:
            - v1-build-cache-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
            - v1-build-cache-{{ .Branch }}
            - v1-build-cache
      - run: mix deps.get
      - save_cache:
          key: v1-dependency-cache-{{ checksum "mix.lock" }}
          paths: deps
      - run: mix credo --strict
      - run: MIX_ENV=test mix coveralls
      - save_cache:
          key: v1-build-cache-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
          paths: _build
      - store_test_results:
          path: _build/test/lib/ex_stone_openbank/test-junit-report.xml
      # - store_artifacts:
      #     path: /tmp/excoveralls
